### PR TITLE
[add]: Added Faculty Register Page

### PR DESCRIPTION
**Pull request by ronaklalwanii**
### **_Didn't have a addFaculty action or controller so haven't done yet_**

### CODE REVIEW

**Comment by Pjha72** [comment]
Add some ss here

**Comment by ronaklalwanii** [comment]
image

**Comment by Pjha72** [comment]
Done

**Comment by ronaklalwanii** [comment]
Functionality is pending you'll have to look into that as I don't have experience with mongo.

**Comment by Pjha72** [comment]
okk

**Comment by Pjha72** [comment]
Add student module registration page

**Comment by ronaklalwanii** [comment]
Yeah, I'll do that by the afternoon I've got some errands to do

**Comment by Pjha72** [comment]
Can you adjust the home button

**Comment by Pjha72** [comment]
In the bottom right corner of the registration page

**Comment by ronaklalwanii** [comment]
Instead of having it outside we can have the back to home button to the right of register. What do you think?

**Comment by Pjha72** [comment]
Fine

**Pull request merged**
